import { CanvasElement, TemplateData } from './types';

function generateId(): string {
  return Math.random().toString(36).substr(2, 9);
}

export const DESIGN_NAMES: Record<number, string> = {
  1: 'كلاسيكي فاخر',
  2: 'عربي إسلامي',
  3: 'عصري مينيمال',
  4: 'رومانسي',
  5: 'بوهيمي',
  6: 'ملكي',
  7: 'طبيعي',
  8: 'راقي',
  9: 'شرقي',
  10: 'معاصر',
};

export const COLOR_SCHEMES: Record<string, { primary: string; secondary: string; accent: string; bg: string; text: string }> = {
  'gold-white':    { primary: '#C9A84C', secondary: '#F5D78E', accent: '#9A7020', bg: '#FFFDF5', text: '#2C1810' },
  'green-gold':    { primary: '#2D6A4F', secondary: '#C9A84C', accent: '#1B4332', bg: '#F0F7F4', text: '#1B3A2D' },
  'black-white':   { primary: '#1A1A1A', secondary: '#444444', accent: '#000000', bg: '#FFFFFF', text: '#111111' },
  'pink-gold':     { primary: '#D4618A', secondary: '#C9A84C', accent: '#A83060', bg: '#FFF5F8', text: '#3D1020' },
  'beige-copper':  { primary: '#C49A6C', secondary: '#E8C9A0', accent: '#8B5E3C', bg: '#FAF5EF', text: '#3C2415' },
  'navy-gold':     { primary: '#0D1B3E', secondary: '#C9A84C', accent: '#06102A', bg: '#F0F2F8', text: '#0D1B3E' },
  'green-beige':   { primary: '#52796F', secondary: '#CAD2C5', accent: '#354F52', bg: '#F4F7F4', text: '#2F3E46' },
  'gray-silver':   { primary: '#6B7280', secondary: '#C0C0C0', accent: '#374151', bg: '#F9FAFB', text: '#1F2937' },
  'burgundy-gold': { primary: '#722F37', secondary: '#C9A84C', accent: '#4A1520', bg: '#FFF5F5', text: '#3D1420' },
  'blue-white':    { primary: '#1D4ED8', secondary: '#93C5FD', accent: '#1E3A8A', bg: '#F0F4FF', text: '#1E3A8A' },
};

export const FONT_OPTIONS = [
  { value: 'Amiri', label: 'Amiri' },
  { value: 'Noto Naskh Arabic', label: 'Noto Naskh Arabic' },
  { value: 'Scheherazade New', label: 'Scheherazade New' },
];

function createBaseElements(scheme: typeof COLOR_SCHEMES['gold-white'], font: string, brideName = 'اسم العروسة', groomName = 'اسم العريس'): CanvasElement[] {
  return [
    {
      id: generateId(),
      type: 'shape',
      name: 'خلفية رئيسية',
      x: 0,
      y: 0,
      width: 800,
      height: 1200,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: true,
      flipX: false,
      flipY: false,
      zIndex: 0,
      shapeType: 'rectangle',
      styles: {
        backgroundColor: scheme.bg,
        borderWidth: 0,
      },
    },
    {
      id: generateId(),
      type: 'shape',
      name: 'إطار ذهبي علوي',
      x: 20,
      y: 20,
      width: 760,
      height: 8,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 1,
      shapeType: 'rectangle',
      styles: { backgroundColor: scheme.primary, borderWidth: 0 },
    },
    {
      id: generateId(),
      type: 'shape',
      name: 'إطار ذهبي سفلي',
      x: 20,
      y: 1172,
      width: 760,
      height: 8,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 1,
      shapeType: 'rectangle',
      styles: { backgroundColor: scheme.primary, borderWidth: 0 },
    },
    {
      id: generateId(),
      type: 'text',
      name: 'عنوان البسملة',
      x: 200,
      y: 60,
      width: 400,
      height: 60,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 2,
      content: 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيم',
      styles: {
        fontFamily: font,
        fontSize: 22,
        fontWeight: '700',
        color: scheme.primary,
        textAlign: 'center',
        lineHeight: 1.6,
      },
    },
    {
      id: generateId(),
      type: 'ornament',
      name: 'زخرفة علوية',
      x: 100,
      y: 130,
      width: 600,
      height: 80,
      rotation: 0,
      opacity: 0.7,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 2,
      ornamentType: 'divider-ornate',
      styles: { color: scheme.primary },
    },
    {
      id: generateId(),
      type: 'text',
      name: 'عنوان الدعوة',
      x: 100,
      y: 230,
      width: 600,
      height: 80,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 3,
      content: 'يسرّنا دعوتكم لحضور حفل زفافنا',
      styles: {
        fontFamily: font,
        fontSize: 26,
        fontWeight: '400',
        color: scheme.text,
        textAlign: 'center',
        lineHeight: 1.8,
      },
    },
    {
      id: generateId(),
      type: 'text',
      name: 'اسم العريس',
      x: 150,
      y: 340,
      width: 500,
      height: 80,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 3,
      content: groomName,
      styles: {
        fontFamily: font,
        fontSize: 48,
        fontWeight: '700',
        color: scheme.primary,
        textAlign: 'center',
        lineHeight: 1.3,
      },
    },
    {
      id: generateId(),
      type: 'text',
      name: 'كلمة و',
      x: 320,
      y: 440,
      width: 160,
      height: 50,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 3,
      content: '❧ و ❧',
      styles: {
        fontFamily: font,
        fontSize: 28,
        fontWeight: '400',
        color: scheme.accent,
        textAlign: 'center',
      },
    },
    {
      id: generateId(),
      type: 'text',
      name: 'اسم العروسة',
      x: 150,
      y: 500,
      width: 500,
      height: 80,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 3,
      content: brideName,
      styles: {
        fontFamily: font,
        fontSize: 48,
        fontWeight: '700',
        color: scheme.primary,
        textAlign: 'center',
        lineHeight: 1.3,
      },
    },
    {
      id: generateId(),
      type: 'ornament',
      name: 'زخرفة وسطى',
      x: 200,
      y: 600,
      width: 400,
      height: 50,
      rotation: 0,
      opacity: 0.6,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 2,
      ornamentType: 'divider-simple',
      styles: { color: scheme.primary },
    },
    {
      id: generateId(),
      type: 'text',
      name: 'تفاصيل الحفل',
      x: 100,
      y: 670,
      width: 600,
      height: 100,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 3,
      content: 'يوم السبت الموافق\n١٥ ربيع الأول ١٤٤٦',
      styles: {
        fontFamily: font,
        fontSize: 24,
        fontWeight: '600',
        color: scheme.text,
        textAlign: 'center',
        lineHeight: 2,
      },
    },
    {
      id: generateId(),
      type: 'text',
      name: 'الوقت',
      x: 250,
      y: 790,
      width: 300,
      height: 50,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 3,
      content: 'الساعة السابعة مساءً',
      styles: {
        fontFamily: font,
        fontSize: 20,
        fontWeight: '500',
        color: scheme.accent,
        textAlign: 'center',
      },
    },
    {
      id: generateId(),
      type: 'text',
      name: 'اسم القاعة',
      x: 100,
      y: 860,
      width: 600,
      height: 60,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 3,
      content: 'قاعة النخيل الفاخرة',
      styles: {
        fontFamily: font,
        fontSize: 28,
        fontWeight: '700',
        color: scheme.primary,
        textAlign: 'center',
      },
    },
    {
      id: generateId(),
      type: 'text',
      name: 'عنوان المكان',
      x: 100,
      y: 930,
      width: 600,
      height: 50,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 3,
      content: 'الرياض - حي العليا - شارع العروبة',
      styles: {
        fontFamily: font,
        fontSize: 18,
        fontWeight: '400',
        color: scheme.text,
        textAlign: 'center',
      },
    },
    {
      id: generateId(),
      type: 'ornament',
      name: 'زخرفة سفلية',
      x: 100,
      y: 1000,
      width: 600,
      height: 80,
      rotation: 180,
      opacity: 0.7,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 2,
      ornamentType: 'divider-ornate',
      styles: { color: scheme.primary },
    },
    {
      id: generateId(),
      type: 'text',
      name: 'نص الختام',
      x: 100,
      y: 1100,
      width: 600,
      height: 60,
      rotation: 0,
      opacity: 1,
      visible: true,
      locked: false,
      flipX: false,
      flipY: false,
      zIndex: 3,
      content: 'نتشرف بحضوركم الكريم وتهانيكم الغالية',
      styles: {
        fontFamily: font,
        fontSize: 18,
        fontWeight: '400',
        color: scheme.text,
        textAlign: 'center',
        lineHeight: 1.6,
      },
    },
  ];
}

export function getBuiltinTemplates(): Omit<TemplateData, 'id' | 'created_at' | 'updated_at'>[] {
  const templates = [];

  const designs = [
    { key: 1, scheme: 'gold-white', font: 'Amiri', name: 'كلاسيكي فاخر', desc: 'تصميم كلاسيكي بألوان ذهبية وبيضاء أنيقة' },
    { key: 2, scheme: 'green-gold', font: 'Noto Naskh Arabic', name: 'عربي إسلامي', desc: 'تصميم إسلامي أصيل بألوان خضراء وذهبية' },
    { key: 3, scheme: 'black-white', font: 'Amiri', name: 'عصري مينيمال', desc: 'تصميم عصري بسيط بالأسود والأبيض' },
    { key: 4, scheme: 'pink-gold', font: 'Scheherazade New', name: 'رومانسي', desc: 'تصميم رومانسي دافئ بألوان وردية وذهبية' },
    { key: 5, scheme: 'beige-copper', font: 'Noto Naskh Arabic', name: 'بوهيمي', desc: 'تصميم بوهيمي عصري بألوان بيج ونحاسية' },
    { key: 6, scheme: 'navy-gold', font: 'Amiri', name: 'ملكي', desc: 'تصميم ملكي فخم بألوان كحلية وذهبية' },
    { key: 7, scheme: 'green-beige', font: 'Noto Naskh Arabic', name: 'طبيعي', desc: 'تصميم طبيعي هادئ بألوان خضراء وبيج' },
    { key: 8, scheme: 'gray-silver', font: 'Amiri', name: 'راقي', desc: 'تصميم راقٍ أنيق بألوان رمادية وفضية' },
    { key: 9, scheme: 'burgundy-gold', font: 'Scheherazade New', name: 'شرقي', desc: 'تصميم شرقي دافئ بألوان بورجوندي وذهبية' },
    { key: 10, scheme: 'blue-white', font: 'Noto Naskh Arabic', name: 'معاصر', desc: 'تصميم معاصر منعش بألوان زرقاء وبيضاء' },
  ];

  for (const d of designs) {
    const scheme = COLOR_SCHEMES[d.scheme];
    templates.push({
      name: d.name,
      description: d.desc,
      design_key: d.key,
      color_scheme: d.scheme,
      font_family: d.font,
      thumbnail_url: '',
      elements: createBaseElements(scheme, d.font),
      canvas_width: 800,
      canvas_height: 1200,
      is_custom: false,
    });
  }

  return templates;
}
